### ISSUE TITLE
是否能增加灵活切换其他在线llm大模型来翻译？

### ISSUE THREAD

**Issue by yuzhou721** [manateelazycat/insert-translated-name#11]
在我的机器上，性能不太行，使用crow和ollama翻译都很慢，是否能增加一种使用llm的方式，灵活切换在线或者本地大模型。比如集成https://github.com/ahyatt/llm 在里面？如果可以的话，我可以提交一个PR

**Comment by manateelazycat** [comment]
欢迎提交pr
