### ISSUE TITLE
insert-translated-name-replace 报错 insert-translated-name-replace-symbol: Symbol’s value as variable is void: insert-translated-name-placeholder-hash

### ISSUE THREAD

**Issue by tangxinfa** [manateelazycat/insert-translated-name#2]
每一个 buffer 需要先用过 `insert-translated-name-insert` 才能用 `insert-translated-name-replace`

**Comment by manateelazycat** [comment]
现在 insert-translated-name-insert 才是命令, insert-translated-name-replace 只是内部工具函数, 不要直接用.

**Comment by tangxinfa** [comment]
但是有时候一上来就想选中几个中文字符串(比如：中文代码注释)，然后转化为英文名称，这还是很有用的

**Comment by tangxinfa** [comment]
封装了一个函数，模拟了一下，凑合着用了：

    (defun my/translate-name ()
        "Insert translated string as variable or function name."
        (interactive)
        (if (use-region-p)
            (progn
              (insert-translated-name-insert nil)
              (kill-region (region-beginning) (region-end))
              (yank)
              (insert " "))
          (insert-translated-name-insert nil)))
