### ISSUE TITLE
Mac OS : executablePath='/Application/Google Chrome.app/Contents/MacOS/Google Chrome'

### ISSUE THREAD

**Issue by Mercurius-Lee** [manateelazycat/insert-translated-name#5]
Mac 系统今天用上了大佬的翻译软件，真是好用！谢谢！
不过我把源码的executablePath改了才能用，有没有简单的办法？
还有就是使用google 或者 DeepL作为翻译引擎，中文翻译成了德文，这个需要从哪里设置？是否像google-this一样有控制的参数。

**Comment by manateelazycat** [comment]
可以把 macOS 的地址发出来， 我看看能否在 TypeScript 直接做一个系统类型判定就好了。

翻译参数 DeepL 可以用 https://www.deepl.com/translator#en/zh/word的形式， 通过URL就可以控制。

**Comment by manateelazycat** [comment]
macOS 路径已经内在支持， 语言翻译参数欢迎发送补丁。 ;)

**Comment by Mercurius-Lee** [comment]
> macOS 路径已经内在支持， 语言翻译参数欢迎发送补丁。 ;)

好的，我这边好好学习，争取有机会做贡献。
