### ISSUE TITLE
deno.land/std@0.159.0

### ISSUE THREAD

**Issue by Mercurius-Lee** [manateelazycat/insert-translated-name#6]
谢谢大佬！
我的Mac 使用的是 deno 1.26.1版本，对应的std库是0.159.0，所以我还是把源码改了，否则失败。不知道linux系统如果deno不一致，是否也需要调整std版本。

**Comment by manateelazycat** [comment]
我的是 deno 1.26.0

**Comment by Mercurius-Lee** [comment]
更新最新commit，并且将deno 更新到1.26.2，mac os的防火墙放行deno，提前打开google对应的DeepL，问题消失。
