### ISSUE TITLE
设置了 insert-translated-name-translate-engine 后并没有生效

### ISSUE THREAD

**Issue by 1925381584** [manateelazycat/insert-translated-name#8]
Version: 3.0

**Comment by manateelazycat** [comment]
至从 google.cn 挂掉以后， 目前只能用 crow-translate 这一个选项了， insert-translated-name-translate-engine 不再有用。

**Comment by 1925381584** [comment]
在我的机器上运行 crow -t  en --json -e lingva 才能正常收到结果，所以是不是需要开放一个选项来选择crow 的 引擎参数

**Comment by manateelazycat** [comment]
可以的，欢迎提交pr

**Comment by 1925381584** [comment]
已经提交了pr了, 等猫哥审核啦

**Comment by manateelazycat** [comment]
感谢补丁， 很赞！
